FROM java:8-jre
MAINTAINER Dsmp lengleng <wangiegie@gmail.com>

ADD ./jar/Dsmp-auth.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=Dsmp-auth", "-Dpinpoint.applicationName=AUTH", "-jar", "/app/Dsmp-auth.jar"]
