FROM java:8-jre
MAINTAINER Dsmp lengleng <wangiegie@gmail.com>

ADD ./jar/Dsmp-upms-service.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx1000m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=Dsmp-upms-service", "-Dpinpoint.applicationName=Dsmp-UPMS-SERVICE", "-jar", "/app/Dsmp-upms-service.jar"]

