FROM java:8-jre
MAINTAINER Dsmp lengleng <wangiegie@gmail.com>

ADD ./jar/Dsmp-gateway.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=Dsmp-gateway", "-Dpinpoint.applicationName=GATEWAY", "-jar", "/app/Dsmp-gateway.jar"]

EXPOSE 9999